#ifndef _DRC_CmdLine_p
#define _DRC_CmdLine_p
#pragma message in DRC_CmdLine.p

/*
 * Prototype file (DRC_CmdLine.p) corresponding to DRC_CmdLine.cpp 
 * (Generated by $Id: DRC_CmdLine.p,v 1.29 2011-03-14 16:49:11-04 alan Exp alan $)
 *
 */

#ifdef __BCPLUSPLUS__
#pragma message C++
  extern "C" {
    void* FindParam(char* Name);
    void ProcessCmdLineArgs(int argc,char **argv);
    void WriteRTFileHeader(FILE* fh,bool batch,char* word);
    bool MatchArg(char *flag,char *arg);
    void TestAndCall(int &idx,int argc,char **argv,int (*func)(char **argv));
    void ErrCmdSwt(char *str);
    int Set_Language(char** arglist);
    int Set_VisualFeatureLetterUnits(char** arglist);
    int Set_PhonemeUnits(char** arglist);
    int Set_SetParameter(char** arglist);
    int Set_ReadParameterFile(char** arglist);
    int Set_SeparateHomophoneFlag(char** arglist);
    int Set_ContinueToMaxCycles(char** arglist);
    int Set_ProcessBatchFile(char** arglist);
    int Set_TestBatchOnly(char** arglist);
    int Set_BatchProcessLimits(char** arglist);
    int Set_MaxIncorrectResults(char** arglist);
    int Set_RepeatSimulation(char** arglist);
    int Set_ActivationFileExt(char** arglist);
    int Set_SaveActivationLvls(char** arglist);
    int Set_ReportExtraInfo(char** arglist);
    int Set_OutputFlags(char** arglist);
    int Set_ReportActGreater(char** arglist);
    int Set_NoOutputFiles(char** arglist);
    int Set_RTFileExtn(char** arglist);
    int Set_OutputDirectory(char** arglist);
    int Set_ReportSimDuration(char** arglist);
    int Set_Verbalize(char** arglist);
    int ListIrregularWords(char** arglist);
    int ListIrregularStressWords(char** arglist);
    int ApplyGPCRules(char** arglist);
    int ListRegularWords(char** arglist);
    int ApplyGPCStressRules(char** arglist);
    int ListWhammies(char** arglist);
    int DisplayHelp(char** arglist);
    int DisplayVersion(char** arglist);
    int ReadCmdLineOptionsFile(char** arglist);
    int Cmd_DspNeighbourhood(char** arglist);
    int Cmd_DspHomographs(char** arglist);
    int Cmd_DspHomophones(char** arglist);
  }
#else
#pragma message C
    extern void* FindParam(char* Name);
    extern void ProcessCmdLineArgs(int argc,char **argv);
    extern void WriteRTFileHeader(FILE* fh,bool batch,char* word);
    extern bool MatchArg(char *flag,char *arg);
    extern void TestAndCall(int &idx,int argc,char **argv,int (*func)(char **argv));
    extern void ErrCmdSwt(char *str);
    extern int Set_Language(char** arglist);
    extern int Set_VisualFeatureLetterUnits(char** arglist);
    extern int Set_PhonemeUnits(char** arglist);
    extern int Set_SetParameter(char** arglist);
    extern int Set_ReadParameterFile(char** arglist);
    extern int Set_SeparateHomophoneFlag(char** arglist);
    extern int Set_ContinueToMaxCycles(char** arglist);
    extern int Set_ProcessBatchFile(char** arglist);
    extern int Set_TestBatchOnly(char** arglist);
    extern int Set_BatchProcessLimits(char** arglist);
    extern int Set_MaxIncorrectResults(char** arglist);
    extern int Set_RepeatSimulation(char** arglist);
    extern int Set_ActivationFileExt(char** arglist);
    extern int Set_SaveActivationLvls(char** arglist);
    extern int Set_ReportExtraInfo(char** arglist);
    extern int Set_OutputFlags(char** arglist);
    extern int Set_ReportActGreater(char** arglist);
    extern int Set_NoOutputFiles(char** arglist);
    extern int Set_RTFileExtn(char** arglist);
    extern int Set_OutputDirectory(char** arglist);
    extern int Set_ReportSimDuration(char** arglist);
    extern int Set_Verbalize(char** arglist);
    extern int ListIrregularWords(char** arglist);
    extern int ListIrregularStressWords(char** arglist);
    extern int ApplyGPCRules(char** arglist);
    extern int ListRegularWords(char** arglist);
    extern int ApplyGPCStressRules(char** arglist);
    extern int ListWhammies(char** arglist);
    extern int DisplayHelp(char** arglist);
    extern int DisplayVersion(char** arglist);
    extern int ReadCmdLineOptionsFile(char** arglist);
    extern int Cmd_DspNeighbourhood(char** arglist);
    extern int Cmd_DspHomographs(char** arglist);
    extern int Cmd_DspHomophones(char** arglist);
#endif

/*
 * End of file DRC_CmdLine.p 
 */
#endif // _DRC_CmdLine_p
